//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportner.Localization.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessagesResource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesResource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sportner.Localization.Resources.ErrorMessagesResource", typeof(ErrorMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Event_NotAuthenticated {
            get {
                return ResourceManager.GetString("Event_NotAuthenticated", resourceCulture);
            }
        }

        public static string Event_NotFound {
            get {
                return ResourceManager.GetString("Event_NotFound", resourceCulture);
            }
        }

        public static string Event_SportNotFound {
            get {
                return ResourceManager.GetString("Event_SportNotFound", resourceCulture);
            }
        }

        public static string Event_SportInactive {
            get {
                return ResourceManager.GetString("Event_SportInactive", resourceCulture);
            }
        }

        public static string Event_UserNotFound {
            get {
                return ResourceManager.GetString("Event_UserNotFound", resourceCulture);
            }
        }

        public static string Event_CannotCreateContent {
            get {
                return ResourceManager.GetString("Event_CannotCreateContent", resourceCulture);
            }
        }

        public static string Event_NotOrganizer {
            get {
                return ResourceManager.GetString("Event_NotOrganizer", resourceCulture);
            }
        }

        public static string Event_AlreadyApplied {
            get {
                return ResourceManager.GetString("Event_AlreadyApplied", resourceCulture);
            }
        }

        public static string Event_OrganizerCannotApply {
            get {
                return ResourceManager.GetString("Event_OrganizerCannotApply", resourceCulture);
            }
        }

        public static string Event_ParticipantNotFound {
            get {
                return ResourceManager.GetString("Event_ParticipantNotFound", resourceCulture);
            }
        }

        public static string Event_NotCompleted {
            get {
                return ResourceManager.GetString("Event_NotCompleted", resourceCulture);
            }
        }

        public static string Event_RemovalReasonNotFound {
            get {
                return ResourceManager.GetString("Event_RemovalReasonNotFound", resourceCulture);
            }
        }

        public static string Event_WaitlistEntryNotFound {
            get {
                return ResourceManager.GetString("Event_WaitlistEntryNotFound", resourceCulture);
            }
        }

        public static string Event_NotAcceptingApplications {
            get {
                return ResourceManager.GetString("Event_NotAcceptingApplications", resourceCulture);
            }
        }

        public static string Event_CapacityFull {
            get {
                return ResourceManager.GetString("Event_CapacityFull", resourceCulture);
            }
        }

        public static string Event_ParticipantAgeNotEligible {
            get {
                return ResourceManager.GetString("Event_ParticipantAgeNotEligible", resourceCulture);
            }
        }

        public static string Event_ParticipantBirthDateMissing {
            get {
                return ResourceManager.GetString("Event_ParticipantBirthDateMissing", resourceCulture);
            }
        }

        public static string Event_InvitationNotFound {
            get {
                return ResourceManager.GetString("Event_InvitationNotFound", resourceCulture);
            }
        }

        public static string Event_ParticipationLocked {
            get {
                return ResourceManager.GetString("Event_ParticipationLocked", resourceCulture);
            }
        }

        public static string Event_AssignmentEmpty {
            get {
                return ResourceManager.GetString("Event_AssignmentEmpty", resourceCulture);
            }
        }

        public static string Event_NotFriends {
            get {
                return ResourceManager.GetString("Event_NotFriends", resourceCulture);
            }
        }

        public static string Event_RelationshipBlocked {
            get {
                return ResourceManager.GetString("Event_RelationshipBlocked", resourceCulture);
            }
        }

        public static string Event_NotOrganizationMember {
            get {
                return ResourceManager.GetString("Event_NotOrganizationMember", resourceCulture);
            }
        }

        public static string Event_FriendAlreadyAssociated {
            get {
                return ResourceManager.GetString("Event_FriendAlreadyAssociated", resourceCulture);
            }
        }
        public static string Organization_NotAuthenticated {
            get {
                return ResourceManager.GetString("Organization_NotAuthenticated", resourceCulture);
            }
        }

        public static string Organization_UserNotFound {
            get {
                return ResourceManager.GetString("Organization_UserNotFound", resourceCulture);
            }
        }

        public static string Organization_CannotCreateContent {
            get {
                return ResourceManager.GetString("Organization_CannotCreateContent", resourceCulture);
            }
        }

        public static string Organization_NotFound {
            get {
                return ResourceManager.GetString("Organization_NotFound", resourceCulture);
            }
        }

        public static string Organization_CityNotFound {
            get {
                return ResourceManager.GetString("Organization_CityNotFound", resourceCulture);
            }
        }

        public static string Organization_InvalidInviteCode {
            get {
                return ResourceManager.GetString("Organization_InvalidInviteCode", resourceCulture);
            }
        }

        public static string Organization_AlreadyMember {
            get {
                return ResourceManager.GetString("Organization_AlreadyMember", resourceCulture);
            }
        }

        public static string Organization_AlreadyPending {
            get {
                return ResourceManager.GetString("Organization_AlreadyPending", resourceCulture);
            }
        }

        public static string Organization_NotApprovedMember {
            get {
                return ResourceManager.GetString("Organization_NotApprovedMember", resourceCulture);
            }
        }

        public static string Organization_CannotManageMembers {
            get {
                return ResourceManager.GetString("Organization_CannotManageMembers", resourceCulture);
            }
        }

        public static string Organization_CannotCreateEvents {
            get {
                return ResourceManager.GetString("Organization_CannotCreateEvents", resourceCulture);
            }
        }

        public static string Organization_CannotModerateMember {
            get {
                return ResourceManager.GetString("Organization_CannotModerateMember", resourceCulture);
            }
        }

        public static string Organization_MemberBlocked {
            get {
                return ResourceManager.GetString("Organization_MemberBlocked", resourceCulture);
            }
        }

        public static string Organization_NotFounder {
            get {
                return ResourceManager.GetString("Organization_NotFounder", resourceCulture);
            }
        }

        public static string Organization_FounderCannotLeave {
            get {
                return ResourceManager.GetString("Organization_FounderCannotLeave", resourceCulture);
            }
        }

        public static string Organization_MemberNotFound {
            get {
                return ResourceManager.GetString("Organization_MemberNotFound", resourceCulture);
            }
        }

        public static string Organization_InviteCodeUnavailable {
            get {
                return ResourceManager.GetString("Organization_InviteCodeUnavailable", resourceCulture);
            }
        }

        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }

        public static string Auth_UsernameTaken {
            get {
                return ResourceManager.GetString("Auth_UsernameTaken", resourceCulture);
            }
        }

        public static string Auth_AccountNotAccessible {
            get {
                return ResourceManager.GetString("Auth_AccountNotAccessible", resourceCulture);
            }
        }

        public static string Auth_InvalidRefreshToken {
            get {
                return ResourceManager.GetString("Auth_InvalidRefreshToken", resourceCulture);
            }
        }

        public static string Auth_ExternalTokenInvalid {
            get {
                return ResourceManager.GetString("Auth_ExternalTokenInvalid", resourceCulture);
            }
        }

        public static string Auth_ExternalRegistrationTokenInvalid {
            get {
                return ResourceManager.GetString("Auth_ExternalRegistrationTokenInvalid", resourceCulture);
            }
        }

        public static string Auth_ExternalLoginAlreadyRegistered {
            get {
                return ResourceManager.GetString("Auth_ExternalLoginAlreadyRegistered", resourceCulture);
            }
        }

        public static string Auth_EmailTaken {
            get {
                return ResourceManager.GetString("Auth_EmailTaken", resourceCulture);
            }
        }

        public static string Auth_EmailRequired {
            get {
                return ResourceManager.GetString("Auth_EmailRequired", resourceCulture);
            }
        }

        public static string Auth_EmailAlreadyVerified {
            get {
                return ResourceManager.GetString("Auth_EmailAlreadyVerified", resourceCulture);
            }
        }

        public static string Auth_EmailVerificationCodeInvalid {
            get {
                return ResourceManager.GetString("Auth_EmailVerificationCodeInvalid", resourceCulture);
            }
        }

        public static string Auth_EmailVerificationCodeExpired {
            get {
                return ResourceManager.GetString("Auth_EmailVerificationCodeExpired", resourceCulture);
            }
        }

        public static string Auth_EmailVerificationCooldown {
            get {
                return ResourceManager.GetString("Auth_EmailVerificationCooldown", resourceCulture);
            }
        }

        public static string Auth_PasswordResetCodeInvalid {
            get {
                return ResourceManager.GetString("Auth_PasswordResetCodeInvalid", resourceCulture);
            }
        }

        public static string Auth_PasswordResetCooldown {
            get {
                return ResourceManager.GetString("Auth_PasswordResetCooldown", resourceCulture);
            }
        }

        public static string Friendship_NotAuthenticated {
            get {
                return ResourceManager.GetString("Friendship_NotAuthenticated", resourceCulture);
            }
        }

        public static string Friendship_UserNotFound {
            get {
                return ResourceManager.GetString("Friendship_UserNotFound", resourceCulture);
            }
        }

        public static string Friendship_NotFound {
            get {
                return ResourceManager.GetString("Friendship_NotFound", resourceCulture);
            }
        }

        public static string Friendship_SelfRequest {
            get {
                return ResourceManager.GetString("Friendship_SelfRequest", resourceCulture);
            }
        }

        public static string Friendship_AlreadyExists {
            get {
                return ResourceManager.GetString("Friendship_AlreadyExists", resourceCulture);
            }
        }

        public static string Friendship_Blocked {
            get {
                return ResourceManager.GetString("Friendship_Blocked", resourceCulture);
            }
        }

        public static string Friendship_NotAddressee {
            get {
                return ResourceManager.GetString("Friendship_NotAddressee", resourceCulture);
            }
        }

        public static string Friendship_NotParticipant {
            get {
                return ResourceManager.GetString("Friendship_NotParticipant", resourceCulture);
            }
        }

        public static string Friendship_NotAccepted {
            get {
                return ResourceManager.GetString("Friendship_NotAccepted", resourceCulture);
            }
        }

        public static string Friendship_NotVisible {
            get {
                return ResourceManager.GetString("Friendship_NotVisible", resourceCulture);
            }
        }

        public static string Post_NotAuthenticated {
            get {
                return ResourceManager.GetString("Post_NotAuthenticated", resourceCulture);
            }
        }

        public static string Post_NotFound {
            get {
                return ResourceManager.GetString("Post_NotFound", resourceCulture);
            }
        }

        public static string Post_UserNotFound {
            get {
                return ResourceManager.GetString("Post_UserNotFound", resourceCulture);
            }
        }

        public static string Post_CannotCreateContent {
            get {
                return ResourceManager.GetString("Post_CannotCreateContent", resourceCulture);
            }
        }

        public static string Post_NotOwner {
            get {
                return ResourceManager.GetString("Post_NotOwner", resourceCulture);
            }
        }

        public static string Post_Forbidden {
            get {
                return ResourceManager.GetString("Post_Forbidden", resourceCulture);
            }
        }

        public static string Post_AlreadyLiked {
            get {
                return ResourceManager.GetString("Post_AlreadyLiked", resourceCulture);
            }
        }

        public static string Post_NotLiked {
            get {
                return ResourceManager.GetString("Post_NotLiked", resourceCulture);
            }
        }

        public static string Post_SelfLike {
            get {
                return ResourceManager.GetString("Post_SelfLike", resourceCulture);
            }
        }

        public static string Post_InvalidMedia {
            get {
                return ResourceManager.GetString("Post_InvalidMedia", resourceCulture);
            }
        }

        public static string Post_MediaNotFound {
            get {
                return ResourceManager.GetString("Post_MediaNotFound", resourceCulture);
            }
        }

        public static string Post_CommentNotFound {
            get {
                return ResourceManager.GetString("Post_CommentNotFound", resourceCulture);
            }
        }

        public static string Post_InvalidCursor {
            get {
                return ResourceManager.GetString("Post_InvalidCursor", resourceCulture);
            }
        }

        public static string Messaging_NotAuthenticated {
            get {
                return ResourceManager.GetString("Messaging_NotAuthenticated", resourceCulture);
            }
        }

        public static string Messaging_ConversationNotFound {
            get {
                return ResourceManager.GetString("Messaging_ConversationNotFound", resourceCulture);
            }
        }

        public static string Messaging_MessageNotFound {
            get {
                return ResourceManager.GetString("Messaging_MessageNotFound", resourceCulture);
            }
        }

        public static string Messaging_NotMember {
            get {
                return ResourceManager.GetString("Messaging_NotMember", resourceCulture);
            }
        }

        public static string Messaging_CannotSend {
            get {
                return ResourceManager.GetString("Messaging_CannotSend", resourceCulture);
            }
        }

        public static string Messaging_ConversationClosed {
            get {
                return ResourceManager.GetString("Messaging_ConversationClosed", resourceCulture);
            }
        }

        public static string Messaging_NotSender {
            get {
                return ResourceManager.GetString("Messaging_NotSender", resourceCulture);
            }
        }

        public static string Messaging_InvalidMedia {
            get {
                return ResourceManager.GetString("Messaging_InvalidMedia", resourceCulture);
            }
        }

        public static string Messaging_InvalidCursor {
            get {
                return ResourceManager.GetString("Messaging_InvalidCursor", resourceCulture);
            }
        }

        public static string Messaging_ReplyNotFound {
            get {
                return ResourceManager.GetString("Messaging_ReplyNotFound", resourceCulture);
            }
        }

        public static string Messaging_PeerNotFound {
            get {
                return ResourceManager.GetString("Messaging_PeerNotFound", resourceCulture);
            }
        }

        public static string Messaging_NotFriends {
            get {
                return ResourceManager.GetString("Messaging_NotFriends", resourceCulture);
            }
        }

        public static string Messaging_Blocked {
            get {
                return ResourceManager.GetString("Messaging_Blocked", resourceCulture);
            }
        }

        public static string Messaging_CannotMessageSelf {
            get {
                return ResourceManager.GetString("Messaging_CannotMessageSelf", resourceCulture);
            }
        }

        public static string Messaging_CannotInvite {
            get {
                return ResourceManager.GetString("Messaging_CannotInvite", resourceCulture);
            }
        }

        public static string Messaging_GroupFull {
            get {
                return ResourceManager.GetString("Messaging_GroupFull", resourceCulture);
            }
        }

        public static string Messaging_InvalidOperation {
            get {
                return ResourceManager.GetString("Messaging_InvalidOperation", resourceCulture);
            }
        }

        public static string Messaging_UserNotFound {
            get {
                return ResourceManager.GetString("Messaging_UserNotFound", resourceCulture);
            }
        }

        public static string Review_NotAuthenticated {
            get {
                return ResourceManager.GetString("Review_NotAuthenticated", resourceCulture);
            }
        }

        public static string Review_NotFound {
            get {
                return ResourceManager.GetString("Review_NotFound", resourceCulture);
            }
        }

        public static string Review_EventNotFound {
            get {
                return ResourceManager.GetString("Review_EventNotFound", resourceCulture);
            }
        }

        public static string Review_EventNotCompleted {
            get {
                return ResourceManager.GetString("Review_EventNotCompleted", resourceCulture);
            }
        }

        public static string Review_NotEligible {
            get {
                return ResourceManager.GetString("Review_NotEligible", resourceCulture);
            }
        }

        public static string Review_SelfReview {
            get {
                return ResourceManager.GetString("Review_SelfReview", resourceCulture);
            }
        }

        public static string Review_AlreadyExists {
            get {
                return ResourceManager.GetString("Review_AlreadyExists", resourceCulture);
            }
        }

        public static string Review_RelationshipBlocked {
            get {
                return ResourceManager.GetString("Review_RelationshipBlocked", resourceCulture);
            }
        }

        public static string Review_NotReviewer {
            get {
                return ResourceManager.GetString("Review_NotReviewer", resourceCulture);
            }
        }

        public static string Sport_NotFound {
            get {
                return ResourceManager.GetString("Sport_NotFound", resourceCulture);
            }
        }

        public static string Sport_NameTaken {
            get {
                return ResourceManager.GetString("Sport_NameTaken", resourceCulture);
            }
        }

        public static string Sport_SlugTaken {
            get {
                return ResourceManager.GetString("Sport_SlugTaken", resourceCulture);
            }
        }

        public static string Sport_InvalidMedia {
            get {
                return ResourceManager.GetString("Sport_InvalidMedia", resourceCulture);
            }
        }

        public static string Profile_NotAuthenticated {
            get {
                return ResourceManager.GetString("Profile_NotAuthenticated", resourceCulture);
            }
        }

        public static string Profile_NotFound {
            get {
                return ResourceManager.GetString("Profile_NotFound", resourceCulture);
            }
        }

        public static string Profile_AlreadyExists {
            get {
                return ResourceManager.GetString("Profile_AlreadyExists", resourceCulture);
            }
        }

        public static string Profile_UsernameTaken {
            get {
                return ResourceManager.GetString("Profile_UsernameTaken", resourceCulture);
            }
        }

        public static string Profile_UsernameChangeTooSoon {
            get {
                return ResourceManager.GetString("Profile_UsernameChangeTooSoon", resourceCulture);
            }
        }

        public static string Profile_BirthDateLocked {
            get {
                return ResourceManager.GetString("Profile_BirthDateLocked", resourceCulture);
            }
        }

        public static string Profile_NotPublic {
            get {
                return ResourceManager.GetString("Profile_NotPublic", resourceCulture);
            }
        }

        public static string Profile_InvalidMedia {
            get {
                return ResourceManager.GetString("Profile_InvalidMedia", resourceCulture);
            }
        }

        public static string Profile_InvalidCity {
            get {
                return ResourceManager.GetString("Profile_InvalidCity", resourceCulture);
            }
        }

        public static string UserSport_NotAuthenticated {
            get {
                return ResourceManager.GetString("UserSport_NotAuthenticated", resourceCulture);
            }
        }

        public static string UserSport_UserNotFound {
            get {
                return ResourceManager.GetString("UserSport_UserNotFound", resourceCulture);
            }
        }

        public static string UserSport_SportNotFound {
            get {
                return ResourceManager.GetString("UserSport_SportNotFound", resourceCulture);
            }
        }

        public static string UserSport_SportInactive {
            get {
                return ResourceManager.GetString("UserSport_SportInactive", resourceCulture);
            }
        }

        public static string UserSport_AlreadyAdded {
            get {
                return ResourceManager.GetString("UserSport_AlreadyAdded", resourceCulture);
            }
        }

        public static string UserSport_NotFound {
            get {
                return ResourceManager.GetString("UserSport_NotFound", resourceCulture);
            }
        }

        public static string SavedLocation_NotAuthenticated {
            get {
                return ResourceManager.GetString("SavedLocation_NotAuthenticated", resourceCulture);
            }
        }

        public static string SavedLocation_UserNotFound {
            get {
                return ResourceManager.GetString("SavedLocation_UserNotFound", resourceCulture);
            }
        }

        public static string SavedLocation_NotFound {
            get {
                return ResourceManager.GetString("SavedLocation_NotFound", resourceCulture);
            }
        }

        public static string Session_NotAuthenticated {
            get {
                return ResourceManager.GetString("Session_NotAuthenticated", resourceCulture);
            }
        }

        public static string Session_UserNotFound {
            get {
                return ResourceManager.GetString("Session_UserNotFound", resourceCulture);
            }
        }

        public static string Session_NotFound {
            get {
                return ResourceManager.GetString("Session_NotFound", resourceCulture);
            }
        }

        public static string Onboarding_NotAuthenticated {
            get {
                return ResourceManager.GetString("Onboarding_NotAuthenticated", resourceCulture);
            }
        }

        public static string Onboarding_UserNotFound {
            get {
                return ResourceManager.GetString("Onboarding_UserNotFound", resourceCulture);
            }
        }

        public static string Onboarding_ProfileRequired {
            get {
                return ResourceManager.GetString("Onboarding_ProfileRequired", resourceCulture);
            }
        }

        public static string Onboarding_SportRequired {
            get {
                return ResourceManager.GetString("Onboarding_SportRequired", resourceCulture);
            }
        }

        public static string Onboarding_PersonalDetailsRequired {
            get {
                return ResourceManager.GetString("Onboarding_PersonalDetailsRequired", resourceCulture);
            }
        }

        public static string Onboarding_AvatarRequired {
            get {
                return ResourceManager.GetString("Onboarding_AvatarRequired", resourceCulture);
            }
        }

        public static string Device_NotAuthenticated {
            get {
                return ResourceManager.GetString("Device_NotAuthenticated", resourceCulture);
            }
        }

        public static string Device_UserNotFound {
            get {
                return ResourceManager.GetString("Device_UserNotFound", resourceCulture);
            }
        }

        public static string Device_NotFound {
            get {
                return ResourceManager.GetString("Device_NotFound", resourceCulture);
            }
        }

        public static string Explore_NotAuthenticated {
            get {
                return ResourceManager.GetString("Explore_NotAuthenticated", resourceCulture);
            }
        }

        public static string Album_NotAuthenticated {
            get {
                return ResourceManager.GetString("Album_NotAuthenticated", resourceCulture);
            }
        }

        public static string Album_NotFound {
            get {
                return ResourceManager.GetString("Album_NotFound", resourceCulture);
            }
        }

        public static string Album_Forbidden {
            get {
                return ResourceManager.GetString("Album_Forbidden", resourceCulture);
            }
        }

        public static string Album_NotOwner {
            get {
                return ResourceManager.GetString("Album_NotOwner", resourceCulture);
            }
        }

        public static string Album_EventNotFound {
            get {
                return ResourceManager.GetString("Album_EventNotFound", resourceCulture);
            }
        }

        public static string Album_NotOrganizer {
            get {
                return ResourceManager.GetString("Album_NotOrganizer", resourceCulture);
            }
        }

        public static string Album_CannotUpload {
            get {
                return ResourceManager.GetString("Album_CannotUpload", resourceCulture);
            }
        }

        public static string Album_InvalidMedia {
            get {
                return ResourceManager.GetString("Album_InvalidMedia", resourceCulture);
            }
        }

        public static string Album_MediaNotFound {
            get {
                return ResourceManager.GetString("Album_MediaNotFound", resourceCulture);
            }
        }

        public static string Album_ProfileAlbumLimit {
            get {
                return ResourceManager.GetString("Album_ProfileAlbumLimit", resourceCulture);
            }
        }

        public static string Album_EventAlbumLimit {
            get {
                return ResourceManager.GetString("Album_EventAlbumLimit", resourceCulture);
            }
        }

        public static string Album_InvalidVisibility {
            get {
                return ResourceManager.GetString("Album_InvalidVisibility", resourceCulture);
            }
        }

        public static string Report_NotAuthenticated {
            get {
                return ResourceManager.GetString("Report_NotAuthenticated", resourceCulture);
            }
        }

        public static string Report_NotFound {
            get {
                return ResourceManager.GetString("Report_NotFound", resourceCulture);
            }
        }

        public static string Report_ReasonNotFound {
            get {
                return ResourceManager.GetString("Report_ReasonNotFound", resourceCulture);
            }
        }

        public static string Report_TargetNotFound {
            get {
                return ResourceManager.GetString("Report_TargetNotFound", resourceCulture);
            }
        }

        public static string Report_AlreadyExists {
            get {
                return ResourceManager.GetString("Report_AlreadyExists", resourceCulture);
            }
        }

        public static string Report_CannotReportSelf {
            get {
                return ResourceManager.GetString("Report_CannotReportSelf", resourceCulture);
            }
        }

        public static string Report_InvalidEntityType {
            get {
                return ResourceManager.GetString("Report_InvalidEntityType", resourceCulture);
            }
        }

        public static string Report_NotOwner {
            get {
                return ResourceManager.GetString("Report_NotOwner", resourceCulture);
            }
        }

        public static string Report_InvalidOperation {
            get {
                return ResourceManager.GetString("Report_InvalidOperation", resourceCulture);
            }
        }

        public static string EventQuestion_NotAuthenticated {
            get {
                return ResourceManager.GetString("EventQuestion_NotAuthenticated", resourceCulture);
            }
        }

        public static string EventQuestion_CannotCreateContent {
            get {
                return ResourceManager.GetString("EventQuestion_CannotCreateContent", resourceCulture);
            }
        }

        public static string EventQuestion_EventNotFound {
            get {
                return ResourceManager.GetString("EventQuestion_EventNotFound", resourceCulture);
            }
        }

        public static string EventQuestion_NotFound {
            get {
                return ResourceManager.GetString("EventQuestion_NotFound", resourceCulture);
            }
        }

        public static string EventQuestion_Closed {
            get {
                return ResourceManager.GetString("EventQuestion_Closed", resourceCulture);
            }
        }

        public static string EventQuestion_OrganizerCannotAsk {
            get {
                return ResourceManager.GetString("EventQuestion_OrganizerCannotAsk", resourceCulture);
            }
        }

        public static string EventQuestion_Blocked {
            get {
                return ResourceManager.GetString("EventQuestion_Blocked", resourceCulture);
            }
        }

        public static string EventQuestion_TooFrequent {
            get {
                return ResourceManager.GetString("EventQuestion_TooFrequent", resourceCulture);
            }
        }

        public static string EventQuestion_InvalidContent {
            get {
                return ResourceManager.GetString("EventQuestion_InvalidContent", resourceCulture);
            }
        }

        public static string Badge_NotAuthenticated {
            get {
                return ResourceManager.GetString("Badge_NotAuthenticated", resourceCulture);
            }
        }

        public static string Badge_UserNotFound {
            get {
                return ResourceManager.GetString("Badge_UserNotFound", resourceCulture);
            }
        }

        public static string Badge_ShowcaseTooMany {
            get {
                return ResourceManager.GetString("Badge_ShowcaseTooMany", resourceCulture);
            }
        }

        public static string Badge_ShowcaseDuplicate {
            get {
                return ResourceManager.GetString("Badge_ShowcaseDuplicate", resourceCulture);
            }
        }

        public static string Badge_ShowcaseNotOwned {
            get {
                return ResourceManager.GetString("Badge_ShowcaseNotOwned", resourceCulture);
            }
        }

        public static string Notification_NotAuthenticated {
            get {
                return ResourceManager.GetString("Notification_NotAuthenticated", resourceCulture);
            }
        }

        public static string Notification_NotFound {
            get {
                return ResourceManager.GetString("Notification_NotFound", resourceCulture);
            }
        }

        public static string Notification_SettingNotFound {
            get {
                return ResourceManager.GetString("Notification_SettingNotFound", resourceCulture);
            }
        }

        public static string Notification_InvalidType {
            get {
                return ResourceManager.GetString("Notification_InvalidType", resourceCulture);
            }
        }

        public static string Notification_InvalidCursor {
            get {
                return ResourceManager.GetString("Notification_InvalidCursor", resourceCulture);
            }
        }

        public static string AppFeedback_NotAuthenticated {
            get {
                return ResourceManager.GetString("AppFeedback_NotAuthenticated", resourceCulture);
            }
        }

        public static string AppFeedback_TooFrequent {
            get {
                return ResourceManager.GetString("AppFeedback_TooFrequent", resourceCulture);
            }
        }

        public static string AppFeedback_InvalidContent {
            get {
                return ResourceManager.GetString("AppFeedback_InvalidContent", resourceCulture);
            }
        }

        public static string Block_NotAuthenticated {
            get {
                return ResourceManager.GetString("Block_NotAuthenticated", resourceCulture);
            }
        }

        public static string Block_UserNotFound {
            get {
                return ResourceManager.GetString("Block_UserNotFound", resourceCulture);
            }
        }

        public static string Block_SelfBlock {
            get {
                return ResourceManager.GetString("Block_SelfBlock", resourceCulture);
            }
        }

        public static string Quest_NotAuthenticated {
            get {
                return ResourceManager.GetString("Quest_NotAuthenticated", resourceCulture);
            }
        }

    }
}
