//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportner.Localization.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationsResource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationsResource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sportner.Localization.Resources.NotificationsResource", typeof(NotificationsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Badge_EarnedTitle {
            get {
                return ResourceManager.GetString("Badge_EarnedTitle", resourceCulture);
            }
        }

        public static string Badge_EarnedBody {
            get {
                return ResourceManager.GetString("Badge_EarnedBody", resourceCulture);
            }
        }

        public static string Quest_CompletedTitle {
            get {
                return ResourceManager.GetString("Quest_CompletedTitle", resourceCulture);
            }
        }

        public static string Quest_CompletedBody {
            get {
                return ResourceManager.GetString("Quest_CompletedBody", resourceCulture);
            }
        }

        public static string OrganizationJoinRequested_Text {
            get {
                return ResourceManager.GetString("OrganizationJoinRequested_Text", resourceCulture);
            }
        }

        public static string OrganizationJoinApproved_Text {
            get {
                return ResourceManager.GetString("OrganizationJoinApproved_Text", resourceCulture);
            }
        }

        public static string OrganizationMemberRemoved_Text {
            get {
                return ResourceManager.GetString("OrganizationMemberRemoved_Text", resourceCulture);
            }
        }

        public static string OrganizationJoinRejected_Text {
            get {
                return ResourceManager.GetString("OrganizationJoinRejected_Text", resourceCulture);
            }
        }

        public static string OrganizationRoleChangedToAdmin_Text {
            get {
                return ResourceManager.GetString("OrganizationRoleChangedToAdmin_Text", resourceCulture);
            }
        }

        public static string OrganizationRoleChangedFromAdmin_Text {
            get {
                return ResourceManager.GetString("OrganizationRoleChangedFromAdmin_Text", resourceCulture);
            }
        }

        public static string OrganizationMemberBlocked_Text {
            get {
                return ResourceManager.GetString("OrganizationMemberBlocked_Text", resourceCulture);
            }
        }

        public static string PostCommented_Title {
            get {
                return ResourceManager.GetString("PostCommented_Title", resourceCulture);
            }
        }

        public static string CommentReplied_Title {
            get {
                return ResourceManager.GetString("CommentReplied_Title", resourceCulture);
            }
        }

        public static string PostLiked_Text {
            get {
                return ResourceManager.GetString("PostLiked_Text", resourceCulture);
            }
        }

        public static string FriendAccepted_Text {
            get {
                return ResourceManager.GetString("FriendAccepted_Text", resourceCulture);
            }
        }

        public static string FriendRequest_Text {
            get {
                return ResourceManager.GetString("FriendRequest_Text", resourceCulture);
            }
        }

        public static string EventQuestionReplied_Title {
            get {
                return ResourceManager.GetString("EventQuestionReplied_Title", resourceCulture);
            }
        }

        public static string EventQuestionAsked_Title {
            get {
                return ResourceManager.GetString("EventQuestionAsked_Title", resourceCulture);
            }
        }

        public static string EventRequestApproved_Title {
            get {
                return ResourceManager.GetString("EventRequestApproved_Title", resourceCulture);
            }
        }

        public static string EventRequestApproved_Body {
            get {
                return ResourceManager.GetString("EventRequestApproved_Body", resourceCulture);
            }
        }

        public static string EventInvitation_Title {
            get {
                return ResourceManager.GetString("EventInvitation_Title", resourceCulture);
            }
        }

        public static string EventInvitation_Body {
            get {
                return ResourceManager.GetString("EventInvitation_Body", resourceCulture);
            }
        }

        public static string EventPromotedFromWaitlist_Title {
            get {
                return ResourceManager.GetString("EventPromotedFromWaitlist_Title", resourceCulture);
            }
        }

        public static string EventRequestRejected_Title {
            get {
                return ResourceManager.GetString("EventRequestRejected_Title", resourceCulture);
            }
        }

        public static string EventRequestRejected_Body {
            get {
                return ResourceManager.GetString("EventRequestRejected_Body", resourceCulture);
            }
        }

        public static string EventCancelled_Title {
            get {
                return ResourceManager.GetString("EventCancelled_Title", resourceCulture);
            }
        }

        public static string EventCancelled_Body {
            get {
                return ResourceManager.GetString("EventCancelled_Body", resourceCulture);
            }
        }

        public static string NewMediaMessage_Fallback {
            get {
                return ResourceManager.GetString("NewMediaMessage_Fallback", resourceCulture);
            }
        }

        public static string EventReminder_Title {
            get {
                return ResourceManager.GetString("EventReminder_Title", resourceCulture);
            }
        }

        public static string EventReminder_Body {
            get {
                return ResourceManager.GetString("EventReminder_Body", resourceCulture);
            }
        }

        public static string EventReviewPrompt_Title {
            get {
                return ResourceManager.GetString("EventReviewPrompt_Title", resourceCulture);
            }
        }

        public static string EventReviewPrompt_Body {
            get {
                return ResourceManager.GetString("EventReviewPrompt_Body", resourceCulture);
            }
        }

        public static string ReviewReceived_Title {
            get {
                return ResourceManager.GetString("ReviewReceived_Title", resourceCulture);
            }
        }

        public static string ReviewReceived_Body {
            get {
                return ResourceManager.GetString("ReviewReceived_Body", resourceCulture);
            }
        }
    }
}
