//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportner.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sportner.Localization.Resources.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Exception_Base_Conflict {
            get {
                return ResourceManager.GetString("Exception_Base_Conflict", resourceCulture);
            }
        }

        public static string Exception_Base_Forbidden {
            get {
                return ResourceManager.GetString("Exception_Base_Forbidden", resourceCulture);
            }
        }

        public static string Exception_Base_InvalidOperation {
            get {
                return ResourceManager.GetString("Exception_Base_InvalidOperation", resourceCulture);
            }
        }

        public static string Exception_Base_NotFound_ByFilter {
            get {
                return ResourceManager.GetString("Exception_Base_NotFound_ByFilter", resourceCulture);
            }
        }

        public static string Exception_Base_Unauthorized {
            get {
                return ResourceManager.GetString("Exception_Base_Unauthorized", resourceCulture);
            }
        }

        public static string Exception_Base_Unexpected {
            get {
                return ResourceManager.GetString("Exception_Base_Unexpected", resourceCulture);
            }
        }

        public static string Validation_Base_Failed {
            get {
                return ResourceManager.GetString("Validation_Base_Failed", resourceCulture);
            }
        }
    }
}
