//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportner.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sportner.Localization.Resources.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already registered..
        /// </summary>
        public static string Exception_Auth_EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("Exception_Auth_EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        public static string Exception_Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Exception_Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An API password has not been set for this account yet. First send the same email and password to /api/auth/register..
        /// </summary>
        public static string Exception_Auth_PasswordNotSet {
            get {
                return ResourceManager.GetString("Exception_Auth_PasswordNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push token updated..
        /// </summary>
        public static string Exception_Auth_PushTokenUpdated {
            get {
                return ResourceManager.GetString("Exception_Auth_PushTokenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string Exception_Auth_UserNotFound {
            get {
                return ResourceManager.GetString("Exception_Auth_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a participation record for this event..
        /// </summary>
        public static string Exception_Event_AlreadyJoined {
            get {
                return ResourceManager.GetString("Exception_Event_AlreadyJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot request to join your own event..
        /// </summary>
        public static string Exception_Event_CannotJoinOwn {
            get {
                return ResourceManager.GetString("Exception_Event_CannotJoinOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event deleted..
        /// </summary>
        public static string Exception_Event_Deleted {
            get {
                return ResourceManager.GetString("Exception_Event_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to perform this action..
        /// </summary>
        public static string Exception_Event_Forbidden {
            get {
                return ResourceManager.GetString("Exception_Event_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event capacity is full..
        /// </summary>
        public static string Exception_Event_Full {
            get {
                return ResourceManager.GetString("Exception_Event_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid latitude and longitude values must be provided..
        /// </summary>
        public static string Exception_Event_InvalidCoordinates {
            get {
                return ResourceManager.GetString("Exception_Event_InvalidCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status must be &apos;approved&apos; or &apos;rejected&apos;..
        /// </summary>
        public static string Exception_Event_InvalidParticipantStatus {
            get {
                return ResourceManager.GetString("Exception_Event_InvalidParticipantStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeframe must be &apos;upcoming&apos;, &apos;past&apos;, or &apos;all&apos;..
        /// </summary>
        public static string Exception_Event_InvalidTimeframe {
            get {
                return ResourceManager.GetString("Exception_Event_InvalidTimeframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latitude and longitude must be sent together..
        /// </summary>
        public static string Exception_Event_LatLonRequired {
            get {
                return ResourceManager.GetString("Exception_Event_LatLonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found..
        /// </summary>
        public static string Exception_Event_NotFound {
            get {
                return ResourceManager.GetString("Exception_Event_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation request not found..
        /// </summary>
        public static string Exception_Event_ParticipantNotFound {
            get {
                return ResourceManager.GetString("Exception_Event_ParticipantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latitude and longitude are required for the radiusKm filter..
        /// </summary>
        public static string Exception_Event_RadiusNeedsCoordinates {
            get {
                return ResourceManager.GetString("Exception_Event_RadiusNeedsCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radiusKm must be greater than zero..
        /// </summary>
        public static string Exception_Event_RadiusPositive {
            get {
                return ResourceManager.GetString("Exception_Event_RadiusPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string Exception_InternalServerError {
            get {
                return ResourceManager.GetString("Exception_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message content cannot be empty..
        /// </summary>
        public static string Exception_Message_Empty {
            get {
                return ResourceManager.GetString("Exception_Message_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this chat..
        /// </summary>
        public static string Exception_Message_Forbidden {
            get {
                return ResourceManager.GetString("Exception_Message_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type must be multipart/form-data. Files cannot be uploaded with application/json. Use FormData and do not set the Content-Type header manually..
        /// </summary>
        public static string Exception_Profile_AvatarContentType {
            get {
                return ResourceManager.GetString("Exception_Profile_AvatarContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only JPEG, PNG, or WebP can be uploaded..
        /// </summary>
        public static string Exception_Profile_AvatarInvalidType {
            get {
                return ResourceManager.GetString("Exception_Profile_AvatarInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar file is required. Form field name must be &apos;file&apos;..
        /// </summary>
        public static string Exception_Profile_AvatarRequired {
            get {
                return ResourceManager.GetString("Exception_Profile_AvatarRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar must be at most 5 MB..
        /// </summary>
        public static string Exception_Profile_AvatarTooLarge {
            get {
                return ResourceManager.GetString("Exception_Profile_AvatarTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading the avatar..
        /// </summary>
        public static string Exception_Profile_AvatarUploadFailed {
            get {
                return ResourceManager.GetString("Exception_Profile_AvatarUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not found..
        /// </summary>
        public static string Exception_Profile_NotFound {
            get {
                return ResourceManager.GetString("Exception_Profile_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already reviewed this user for this event..
        /// </summary>
        public static string Exception_Review_AlreadyExists {
            get {
                return ResourceManager.GetString("Exception_Review_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only users who took part in the event can review each other..
        /// </summary>
        public static string Exception_Review_NotParticipants {
            get {
                return ResourceManager.GetString("Exception_Review_NotParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot review yourself..
        /// </summary>
        public static string Exception_Review_Self {
            get {
                return ResourceManager.GetString("Exception_Review_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user to review was not found..
        /// </summary>
        public static string Exception_Review_UserNotFound {
            get {
                return ResourceManager.GetString("Exception_Review_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized..
        /// </summary>
        public static string Exception_Unauthorized {
            get {
                return ResourceManager.GetString("Exception_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to join &apos;{0}&apos; was approved..
        /// </summary>
        public static string Notification_JoinApproved_Body {
            get {
                return ResourceManager.GetString("Notification_JoinApproved_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Approved.
        /// </summary>
        public static string Notification_JoinApproved_Title {
            get {
                return ResourceManager.GetString("Notification_JoinApproved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to join &apos;{0}&apos; was rejected..
        /// </summary>
        public static string Notification_JoinRejected_Body {
            get {
                return ResourceManager.GetString("Notification_JoinRejected_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Rejected.
        /// </summary>
        public static string Notification_JoinRejected_Title {
            get {
                return ResourceManager.GetString("Notification_JoinRejected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wants to join your event &apos;{1}&apos;..
        /// </summary>
        public static string Notification_JoinRequest_Body {
            get {
                return ResourceManager.GetString("Notification_JoinRequest_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Join Request.
        /// </summary>
        public static string Notification_JoinRequest_Title {
            get {
                return ResourceManager.GetString("Notification_JoinRequest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user.
        /// </summary>
        public static string Notification_RequesterFallback {
            get {
                return ResourceManager.GetString("Notification_RequesterFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content must be at most 2000 characters..
        /// </summary>
        public static string Validation_Content_MaxLength {
            get {
                return ResourceManager.GetString("Validation_Content_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is required..
        /// </summary>
        public static string Validation_Content_Required {
            get {
                return ResourceManager.GetString("Validation_Content_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid..
        /// </summary>
        public static string Validation_Email_Invalid {
            get {
                return ResourceManager.GetString("Validation_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Validation_Email_Required {
            get {
                return ResourceManager.GetString("Validation_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date is required..
        /// </summary>
        public static string Validation_EventDate_Required {
            get {
                return ResourceManager.GetString("Validation_EventDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event id is required..
        /// </summary>
        public static string Validation_EventId_Required {
            get {
                return ResourceManager.GetString("Validation_EventId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required..
        /// </summary>
        public static string Validation_FullName_Required {
            get {
                return ResourceManager.GetString("Validation_FullName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude is required..
        /// </summary>
        public static string Validation_Latitude_Required {
            get {
                return ResourceManager.GetString("Validation_Latitude_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude is required..
        /// </summary>
        public static string Validation_Longitude_Required {
            get {
                return ResourceManager.GetString("Validation_Longitude_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max players must be between 2 and 100..
        /// </summary>
        public static string Validation_MaxPlayers_Range {
            get {
                return ResourceManager.GetString("Validation_MaxPlayers_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters..
        /// </summary>
        public static string Validation_Password_MinLength {
            get {
                return ResourceManager.GetString("Validation_Password_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Validation_Password_Required {
            get {
                return ResourceManager.GetString("Validation_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push token is required..
        /// </summary>
        public static string Validation_PushToken_Required {
            get {
                return ResourceManager.GetString("Validation_PushToken_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating must be between 1 and 5..
        /// </summary>
        public static string Validation_Rating_Range {
            get {
                return ResourceManager.GetString("Validation_Rating_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed user id is required..
        /// </summary>
        public static string Validation_ReviewedId_Required {
            get {
                return ResourceManager.GetString("Validation_ReviewedId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport type is required..
        /// </summary>
        public static string Validation_SportType_Required {
            get {
                return ResourceManager.GetString("Validation_SportType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required..
        /// </summary>
        public static string Validation_Status_Required {
            get {
                return ResourceManager.GetString("Validation_Status_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string Validation_Title_Required {
            get {
                return ResourceManager.GetString("Validation_Title_Required", resourceCulture);
            }
        }
    }
}
