namespace Sportner.Domain.Common.Enums;

public enum NotificationType : short
{
    FriendRequest = 0,
    FriendAccepted = 1,
    EventInvitation = 2,
    EventRequestApproved = 3,
    EventRequestRejected = 4,
    EventReminder = 5,
    EventCancelled = 6,
    PostLiked = 7,
    PostCommented = 8,
    CommentReplied = 9,
    BadgeEarned = 10,
    NewMessage = 11,
    System = 12,
    QuestCompleted = 13,
    EventQuestionAsked = 14,
    EventQuestionReplied = 15,
    OrganizationJoinRequested = 16,
    OrganizationJoinApproved = 17,
    OrganizationJoinRejected = 18,
    OrganizationRoleChanged = 19,
    OrganizationMemberRemoved = 20,
    OrganizationMemberBlocked = 21,
    EventReviewPrompt = 22,
    ReviewReceived = 23,
    OrganizationMemberJoined = 24,
    EventInvitationAccepted = 25,
    EventInvitationDeclined = 26,
    EventParticipationCancelled = 27,
    EventParticipantRemoved = 28,
    EventScheduleUpdated = 29,
    EventLocationUpdated = 30,
    EventFeeUpdated = 31,
    EventCapacityUpdated = 32,
    ConversationMemberAdded = 33,
    EventUpdated = 34
}
